-- 1) habits table
create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  description text not null default '',
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

-- 2) daily_logs table
create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  log_date date not null default current_date,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint daily_logs_unique_per_day unique (user_id, habit_id, log_date)
);

alter table public.habits enable row level security;
alter table public.daily_logs enable row level security;

-- 3) RsLS policies for habit
create policy "Users can view their own habits"
on public.habits for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own habits"
on public.habits for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own habits"
on public.habits for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own habits"
on public.habits for delete
to authenticated
using (auth.uid() = user_id);

-- 4) RLS policies for daily_logs
create policy "Users can view their own daily logs"
on public.daily_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own daily logs"
on public.daily_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own daily logs"
on public.daily_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own daily logs"
on public.daily_logs for delete
to authenticated
using (auth.uid() = user_id);

-- 5) Seed example rows (replace UUID values with real auth.user ids)
-- insert into public.habits (user_id, name, description, completed)
-- values
--   ('11111111-1111-1111-1111-111111111111', 'Drink Water', 'Eight glasses today', false),
--   ('11111111-1111-1111-1111-111111111111', 'Read 20 Minutes', 'Finish the current chapter', true),
--   ('22222222-2222-2222-2222-222222222222', 'Workout', '30 minute session', false);
--
-- insert into public.daily_logs (user_id, habit_id, log_date, completed)
-- values
--   ('11111111-1111-1111-1111-111111111111', 1, current_date, true),
--   ('11111111-1111-1111-1111-111111111111', 2, current_date, true);

-- 6) Example query to prove a user only sees their own rows
-- select * from public.habits where user_id = auth.uid();
